// src/resource.status.tsx
import { RequestStatus } from './resource'
import { ModelError } from './model.error'
import * as tsx from 'vue-tsx-support'
import Component from 'vue-class-component'

export interface ResourceStatusProps {
  status: RequestStatus
  label?: string
}

@Component({
  props: {
    status: {
      required: true,
    },
    label: {},
  },
})
export class ResourceStatus extends tsx.Component<ResourceStatusProps> {
  status!: RequestStatus
  label?: string

  renderError() {
    if (this.status.error.status == 422) {
      return <ModelError errors={this.status.error.body} />
    } else if (this.status.error.status == 500) {
      if (this.status.error.body) {
        return (
          <b-alert show variant="danger">
            {this.status.error.body.error}
          </b-alert>
        )
      } else {
        return (
          <b-alert show variant="danger">
            Something went wrong: Server returned Error 500
          </b-alert>
        )
      }
    } else if (this.status.error.status == 'error') {
      return (
        <b-alert show variant="danger">
          {this.status.error.error}
        </b-alert>
      )
    } else {
      return <pre>{this.status}</pre>
    }
  }

  render() {
    if (this.status) {
      return (
        <div style="position: relative">
          {this.status.start ? (
            <b-alert style="position: absolute; z-index: 99;" show variant="info">
              Loading {this.label} ...
              <font-awesome-icon icon="spinner" pulse />
            </b-alert>
          ) : null}
          {this.status.ready ? (
            <div>
              <slot name="ready" />
            </div>
          ) : null}
          {this.status.error ? <div>{this.renderError()}</div> : null}
        </div>
      )
    } else {
      return <div />
    }
  }
}

// src/resource.status.vue
<template lang="pug">
  div.status(v-if="status")
    b-alert.loading(show variant="info" v-if="status.start")
      | Loading {{label}} ...
      font-awesome-icon(icon="spinner" pulse)
    div(v-if="status.ready")
      slot(name="ready")
    div(v-if="status.error")
      template(v-if="status.error.status === 422")
        rr-model-error(:errors="status.error.body")
      template(v-else-if="status.error.status === 500")
        template(v-if="status.error.body")
          b-alert(show variant="danger") {{status.error.body.error}}
        template(v-else)
          b-alert(show variant="danger") Something went wrong: Server returned Error 500
      template(v-else)
        pre {{status}}
</template>
<script>
export default {
  props: {
    status: {
      required: true,
    },
    label: {},
  },
  data() {
    return {}
  },
}
</script>
<style scoped>
.status {
  position: relative;
}
.status .loading {
  position: absolute;
  z-index: 99;
}
</style>
